background=color
background-color=000

volume-max=600
title=${audio-bitrate} ${video-bitrate} :: ${filename}
no-audio-display
gapless-audio=yes
prefetch-playlist=yes

# Selectively quieten msg categories.  Keeps regular scrollback from growing
# out of control.
msg-level=all=status,ao=error,vo=error,playlist=error,frame_info=error,ffmpeg=error,sub=error

# Force console script load despite no OSD
load-console=yes

screenshot-directory=~/pics/mpv/
screenshot-template=mpv-%F-%p

input-ipc-server=~/.config/mpv/mpv.socket


osd-font-size=20
sub-font=Sans
sub-font-size=55
sub-border-size=3
sub-scale-with-window=no

save-position-on-quit

include=~/.config/mpv/platform.conf

alang=eng,en,jp,jpn
slang=eng,en

[photo]
pause

[gif]
loop-file=inf

[extension.jpg]
profile=photo

[extension.png]
profile=photo

[extension.gif]
profile=gif

[extension.webm]
profile=gif

[media-server]
idle
keep-open
input-ipc-server=~/.config/mpv/media-server.socket
input-commands=print-text "MPV media server: ${options/input-ipc-server}"

[big-cache]
cache=yes
demuxer-max-bytes=512MiB
demuxer-readahead-secs=20

[stream]
profile=big-cache
cache-secs=10
cache-pause-initial
